#!/usr/bin/env node
/**
 * scripts/generate-assets.ts
 *
 * Runs the STATEKEEP image prompt library through OpenAI images.generate
 * and writes the results to web/public/generated/<id>.png.
 *
 * Usage:
 *   OPENAI_API_KEY=sk-... pnpm tsx scripts/generate-assets.ts
 *
 * Honest path: if OPENAI_API_KEY is not set, this exits with a message and
 * does NOT create fake images. Nothing under public/generated/*.png should
 * ever be committed unless it was generated by this script with a real key.
 */
import fs from "node:fs";
import path from "node:path";
import { PROMPTS } from "../lib/image-prompts";

const OUT_DIR = path.resolve(__dirname, "..", "public", "generated");

async function main() {
  const key = process.env.OPENAI_API_KEY;
  if (!key) {
    console.error(
      "\n[generate-assets] OPENAI_API_KEY is not set — refusing to run.\n" +
        "                   Set the env var and rerun. This script never writes fake images.\n",
    );
    process.exit(1);
  }

  fs.mkdirSync(OUT_DIR, { recursive: true });

  const only = process.argv[2]; // optional filter: --id=hero or just id
  const filter = only?.replace(/^--id=/, "");
  const list = filter ? PROMPTS.filter((p) => p.id === filter) : PROMPTS;

  if (list.length === 0) {
    console.error(`[generate-assets] No prompts match ${filter}`);
    process.exit(1);
  }

  for (const p of list) {
    console.log(`[generate-assets] ${p.id} (${p.size}) — ${p.purpose}`);

    const res = await fetch("https://api.openai.com/v1/images/generations", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        Authorization: `Bearer ${key}`,
      },
      body: JSON.stringify({
        model: "gpt-image-1",
        prompt: p.prompt,
        size: p.size,
        n: 1,
      }),
    });

    if (!res.ok) {
      const t = await res.text();
      console.error(`[generate-assets] ${p.id} FAILED (${res.status}): ${t.slice(0, 400)}`);
      process.exit(2);
    }

    const json = (await res.json()) as { data?: Array<{ b64_json?: string; url?: string }> };
    const item = json.data?.[0];
    if (!item?.b64_json && !item?.url) {
      console.error(`[generate-assets] ${p.id} FAILED: no image payload`);
      process.exit(2);
    }

    let buf: Buffer;
    if (item.b64_json) {
      buf = Buffer.from(item.b64_json, "base64");
    } else {
      const dl = await fetch(item.url!);
      if (!dl.ok) {
        console.error(`[generate-assets] ${p.id} FAILED: download ${dl.status}`);
        process.exit(2);
      }
      buf = Buffer.from(await dl.arrayBuffer());
    }

    if (buf.byteLength < 10_000) {
      console.error(`[generate-assets] ${p.id} FAILED: image < 10KB (${buf.byteLength} bytes) — suspicious, refusing to write`);
      process.exit(2);
    }

    const out = path.join(OUT_DIR, `${p.id}.png`);
    fs.writeFileSync(out, buf);
    console.log(`[generate-assets] wrote ${out} (${(buf.byteLength / 1024).toFixed(1)} KB)`);
  }
}

main().catch((e) => {
  console.error("[generate-assets] fatal:", e);
  process.exit(3);
});
